package moe.antimony.hoshi.features.sasayaki

import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

class SasayakiMediaSessionSourceTest {
    @Test
    fun mediaSessionPublishesAudiobookTransportControlsForSystemUi() {
        val source = File("src/main/java/moe/antimony/hoshi/features/sasayaki/SasayakiMediaSession.kt").readText()

        assertFalse(source.contains("import android.media.MediaMetadata"))
        assertFalse(source.contains("import android.media.session.MediaSession"))
        assertFalse(source.contains("import android.media.session.PlaybackState"))
        assertTrue(source.contains("import android.app.Notification"))
        assertTrue(source.contains("import android.app.NotificationChannel"))
        assertTrue(source.contains("import android.app.NotificationManager"))
        assertTrue(source.contains("import android.graphics.Bitmap"))
        assertTrue(source.contains("import android.graphics.BitmapFactory"))
        assertTrue(source.contains("import androidx.core.app.NotificationCompat"))
        assertTrue(source.contains("import androidx.media3.common.ForwardingSimpleBasePlayer"))
        assertTrue(source.contains("import androidx.media3.common.MediaItem"))
        assertTrue(source.contains("import androidx.media3.common.MediaMetadata"))
        assertTrue(source.contains("import androidx.media3.common.Player"))
        assertTrue(source.contains("import androidx.media3.session.CommandButton"))
        assertTrue(source.contains("import androidx.media3.session.MediaSession"))
        assertTrue(source.contains("import androidx.media3.session.MediaStyleNotificationHelper"))
        assertFalse(source.contains("import androidx.media3.session.SessionCommand"))
        assertFalse(source.contains("import androidx.media3.session.SessionCommands"))
        assertFalse(source.contains("import androidx.media3.session.SessionResult"))
        assertTrue(source.contains("MediaSession.Builder(appContext, sessionPlayer)"))
        assertTrue(source.contains("private class SasayakiSessionPlayer("))
        assertTrue(source.contains("override fun handleSetPlayWhenReady(playWhenReady: Boolean)"))
        assertTrue(source.contains("override fun handleSeek("))
        assertTrue(source.contains("onPlay()"))
        assertTrue(source.contains("onPause()"))
        assertTrue(source.contains("onSeekTo(positionMs)"))
        assertTrue(source.contains("onSkipToPrevious()"))
        assertTrue(source.contains("onSkipToNext()"))
        assertTrue(source.contains("MediaStyleNotificationHelper.MediaStyle(session)"))
        assertTrue(source.contains("notificationManager.notify(NotificationId, notification)"))
        assertTrue(source.contains("notificationManager.cancel(NotificationId)"))
        assertTrue(source.contains("Player.COMMAND_PLAY_PAUSE"))
        assertTrue(source.contains("Player.COMMAND_SEEK_IN_CURRENT_MEDIA_ITEM"))
        assertTrue(source.contains("Player.COMMAND_SEEK_TO_PREVIOUS"))
        assertTrue(source.contains("Player.COMMAND_SEEK_TO_NEXT"))
        assertTrue(source.contains("CommandButton.Builder(CommandButton.ICON_PREVIOUS)"))
        assertTrue(source.contains(".setPlayerCommand(Player.COMMAND_SEEK_TO_PREVIOUS)"))
        assertTrue(source.contains("CommandButton.Builder(CommandButton.ICON_NEXT)"))
        assertTrue(source.contains(".setPlayerCommand(Player.COMMAND_SEEK_TO_NEXT)"))
        assertFalse(source.contains(".setSessionCommand("))
        assertFalse(source.contains("override fun onCustomCommand("))
        assertTrue(source.contains("Player.COMMAND_SEEK_TO_PREVIOUS,"))
        assertTrue(source.contains("Player.COMMAND_SEEK_TO_PREVIOUS_MEDIA_ITEM"))
        assertTrue(source.contains("Player.COMMAND_SEEK_TO_NEXT,"))
        assertTrue(source.contains("Player.COMMAND_SEEK_TO_NEXT_MEDIA_ITEM"))
        assertTrue(source.contains("MediaMetadata.Builder()"))
        assertTrue(source.contains("setTitle(title)"))
        assertTrue(source.contains("setArtworkData("))
        assertTrue(source.contains("setLargeIcon(artwork)"))
        assertTrue(source.contains("fun loadCoverArt(file: File?): Bitmap?"))
        assertTrue(source.contains("BitmapFactory.decodeFile(file.absolutePath"))
        assertTrue(source.contains("session.release()"))
    }

    @Test
    fun sasayakiPlayerUsesMediaSessionHandleBoundary() {
        val source = File("src/main/java/moe/antimony/hoshi/features/sasayaki/SasayakiPlaybackController.kt").readText()
        val restoreController = File("src/main/java/moe/antimony/hoshi/features/sasayaki/SasayakiAudioRestoreController.kt").readText()
        val handleCoordinator = File("src/main/java/moe/antimony/hoshi/features/sasayaki/SasayakiMediaSessionHandleCoordinator.kt").readText()
        val restoreAudio = source.substringAfter("private fun restoreAudio()")
            .substringBefore("private fun tick()")
        val startPlayback = source.substringAfter("private fun startPlayback()")
            .substringBefore("private fun seek(")
        val pausePlayback = source.substringAfter("override fun pausePlayback(")
            .substringBefore("fun nextCue()")
        val teardown = source.substringAfter("private fun teardownPlayer(clearCue: Boolean)")

        assertTrue(source.contains("bookTitle: String?"))
        assertTrue(source.contains("bookCoverFile: File?"))
        assertTrue(source.contains("private val mediaSessionHandle = SasayakiMediaSessionHandleCoordinator()"))
        assertTrue(source.contains("private val mediaSessionPublishing = SasayakiMediaSessionPublishingCoordinator("))
        assertTrue(source.contains("private val audioRestoreResult = SasayakiAudioRestoreResultCoordinator("))
        assertTrue(source.contains("private val audioRestoreWorkflow = SasayakiAudioRestoreWorkflowCoordinator("))
        assertFalse(source.contains("private var mediaSession: SasayakiMediaSessionHandle? = null"))
        assertTrue(handleCoordinator.contains("private var mediaSession: SasayakiMediaSessionHandle? = null"))
        assertTrue(source.contains("private val audioRestore = SasayakiAudioRestoreController("))
        assertTrue(restoreAudio.contains("releaseExistingMediaSession = mediaSessionHandle::releaseExisting"))
        assertTrue(restoreAudio.contains("audioRestoreWorkflow.restore("))
        assertFalse(restoreAudio.contains("audioRestoreResult.handleSuccess("))
        assertFalse(restoreAudio.contains("mediaSessionHandle.replace(result.mediaSession)"))
        assertTrue(restoreController.contains("AndroidSasayakiMediaSessionHandle("))
        assertTrue(restoreController.contains("title = bookTitle ?: bookRoot.name"))
        assertTrue(restoreController.contains("artworkFile = bookCoverFile"))
        assertFalse(restoreAudio.contains("SasayakiMediaSession("))
        assertFalse(restoreAudio.contains("SasayakiMediaSession.loadCoverArt(bookCoverFile)"))
        assertTrue(source.contains("private val playbackStart = SasayakiPlaybackStartCoordinator("))
        assertTrue(startPlayback.contains("playbackStart.start("))
        assertTrue(startPlayback.contains("updateMediaSession = ::updateMediaSession"))
        assertFalse(startPlayback.contains("mediaSessionPublishing.activate()"))
        assertFalse(startPlayback.contains("mediaSessionHandle.activate()"))
        assertTrue(pausePlayback.contains("updateMediaSession = ::updateMediaSession"))
        assertTrue(source.contains("private fun updateMediaSession()"))
        assertTrue(source.contains("mediaSessionPublishing.update("))
        assertFalse(source.contains("private fun updateMediaSession() {\n        mediaSessionHandle.update("))
        assertTrue(source.contains("private val playbackTeardown = SasayakiPlaybackTeardownCoordinator("))
        assertTrue(teardown.contains("playbackTeardown.teardown("))
        assertFalse(teardown.contains("mediaSessionHandle.releaseAndClear()"))
    }

    @Test
    fun mediaSessionHandleWrapsMedia3SessionImplementation() {
        val source = File("src/main/java/moe/antimony/hoshi/features/sasayaki/SasayakiMediaSessionController.kt").readText()
        val handle = source.substringAfter("class AndroidSasayakiMediaSessionHandle(")

        assertTrue(source.contains("interface SasayakiMediaSessionHandle"))
        assertTrue(source.contains("player: Player"))
        assertTrue(source.contains("fun activate()"))
        assertTrue(source.contains("fun update("))
        assertTrue(source.contains("fun release()"))
        assertTrue(handle.contains("private val session = SasayakiMediaSession("))
        assertTrue(handle.contains("player = player"))
        assertTrue(handle.contains("artwork = SasayakiMediaSession.loadCoverArt(artworkFile)"))
        assertTrue(handle.contains("onPlay = onPlay"))
        assertTrue(handle.contains("onPause = onPause"))
        assertTrue(handle.contains("onSeekTo = onSeekTo"))
        assertTrue(handle.contains("override fun activate()"))
        assertTrue(handle.contains("session.activate()"))
        assertTrue(handle.contains("override fun update("))
        assertTrue(handle.contains("session.update("))
        assertTrue(handle.contains("override fun release()"))
        assertTrue(handle.contains("session.release()"))
    }

    @Test
    fun mediaSessionActivityReturnsToExistingReaderTask() {
        val source = File("src/main/java/moe/antimony/hoshi/features/sasayaki/SasayakiMediaSession.kt").readText()
        val manifest = File("src/main/AndroidManifest.xml").readText()
        val contentIntent = source.substringAfter("private fun contentIntent()")
            .substringBefore("companion object")

        assertTrue(manifest.contains("android:launchMode=\"singleTop\""))
        assertTrue(source.contains("contentIntent()?.let { setSessionActivity(it) }"))
        assertTrue(contentIntent.contains("Intent.FLAG_ACTIVITY_SINGLE_TOP"))
        assertTrue(contentIntent.contains("Intent.FLAG_ACTIVITY_REORDER_TO_FRONT"))
        assertTrue(contentIntent.contains("PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE"))
    }
}
